### PR TITLE
Remove "consistent-return" rule

### PR DESCRIPTION
**Pull request by christophercliff**
This is inconsistent with our "return early" policy.

### CODE REVIEW

**Comment by maxkostow** [comment]
You can and should still return a consistent value.

**Comment by christophercliff** [comment]
You shouldn't have a function return inconsistent types, but I think it's pretty useful to have a function that returns a value *or* `undefined`.

**Comment by maxkostow** [comment]
I think the rule is fine if you just do `return void 0` or `return null`

**Comment by christophercliff** [comment]
You prefer `return void 0`?!

**Comment by gmathieu** [comment]
`return undefined` so this rule is met: http://eslint.org/docs/rules/no-void

We can probably close this PR after #6

**Pull request closed without merging**
